services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ./frontend:/app
      # Prevent host node_modules from overwriting container node_modules
      - /app/node_modules
      # Persist .next folder between runs
      - /app/.next
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
